### ISSUE TITLE
rm_rf(/nixfs): Function not implemented

### ISSUE THREAD

**Issue by badly-drawn-wizards** [illustris/nixfs#1]
On a `nixos-rebuild switch` it appears NixOS tries to remove the mounted `/nixfs`. This causes only a warning, but perhaps during the switch it should be unmounted first or declared in some way.

My NixOS is here, but with regards to this NixFS I only just enable it:
https://github.com/badly-drawn-wizards/dotfiles/blob/master/LICENSE

**Comment by illustris** [comment]
This is caused by the `D` at https://github.com/illustris/nixfs/blob/74c605f1320252b4bd5b44e4d66d45bec72be3a7/flake.nix#L56

I made the change in https://github.com/illustris/nixfs/commit/74c605f1320252b4bd5b44e4d66d45bec72be3a7, assuming systemd-tmpfiles would clean up the folder if the tmpfile rule was removed. I was wrong about how that works. Reverting it.
